
/* Do not modify this file - it is autogenerated by makecmds */

static void initcmds(void)
{
    struct command *cmd;
    
    cmd = makecmd(L"lssr");
    addresp(cmd, 200, RESP_STR, RESP_STR, RESP_STR, RESP_INT, RESP_INT, RESP_INT, RESP_FLOAT, RESP_STR, RESP_END);
    addresp(cmd, 201, RESP_END);
    addresp(cmd, 514, RESP_END);
    cmd = makecmd(L"lssrch");
    addresp(cmd, 200, RESP_INT, RESP_INT, RESP_INT, RESP_INT, RESP_END);
    addresp(cmd, 201, RESP_END);
    cmd = makecmd(L"shutdown");
    addresp(cmd, 200, RESP_END);
    addresp(cmd, 502, RESP_END);
    cmd = makecmd(L"quit");
    addresp(cmd, 200, RESP_END);
    cmd = makecmd(L"lsauth");
    addresp(cmd, 200, RESP_STR, RESP_END);
    addresp(cmd, 201, RESP_END);
    cmd = makecmd(L"login");
    addresp(cmd, 200, RESP_END);	/* Success */
    addresp(cmd, 300, RESP_STR, RESP_END);	/* Auto (think GSS-API) */
    addresp(cmd, 301, RESP_STR, RESP_END);	/* No echo */
    addresp(cmd, 302, RESP_STR, RESP_END);	/* Echo */
    addresp(cmd, 303, RESP_STR, RESP_END);	/* Info message */
    addresp(cmd, 304, RESP_STR, RESP_END);	/* Error message */
    addresp(cmd, 501, RESP_END);
    addresp(cmd, 503, RESP_END);	/* Already logging in */
    addresp(cmd, 504, RESP_END);	/* Charset error */
    addresp(cmd, 505, RESP_DSC, RESP_STR, RESP_END);	/* Back-end error */
    addresp(cmd, 506, RESP_END);	/* Authentication error */
    addresp(cmd, 508, RESP_END);	/* No such authentication mechanism */
    cmd = makecmd(L"pass");
    addresp(cmd, 200, RESP_END);
    addresp(cmd, 300, RESP_STR, RESP_END);
    addresp(cmd, 301, RESP_STR, RESP_END);
    addresp(cmd, 302, RESP_STR, RESP_END);
    addresp(cmd, 303, RESP_STR, RESP_END);
    addresp(cmd, 304, RESP_STR, RESP_END);
    addresp(cmd, 504, RESP_END);
    addresp(cmd, 505, RESP_DSC, RESP_STR, RESP_END);
    addresp(cmd, 506, RESP_END);
    addresp(cmd, 507, RESP_END);	/* Data not expected */
    cmd = makecmd(L"cnct");
    addresp(cmd, 200, RESP_END);
    addresp(cmd, 502, RESP_END);
    addresp(cmd, 504, RESP_END);
    addresp(cmd, 509, RESP_END);
    addresp(cmd, 511, RESP_END);
    cmd = makecmd(L"lsnodes");
    addresp(cmd, 200, RESP_INT, RESP_STR, RESP_STR, RESP_INT, RESP_INT, RESP_END);
    addresp(cmd, 201, RESP_END);
    addresp(cmd, 502, RESP_END);
    cmd = makecmd(L"dcnct");
    addresp(cmd, 200, RESP_END);
    addresp(cmd, 502, RESP_END);
    addresp(cmd, 510, RESP_END);
    cmd = makecmd(L"lspeers");
    addresp(cmd, 200, RESP_STR, RESP_STR, RESP_END);	/* Peer ID and nick are standardized, so they can be here -- the rest have to be extracted manually */
    addresp(cmd, 201, RESP_END);
    addresp(cmd, 510, RESP_END);
    cmd = makecmd(L"lspa");
    addresp(cmd, 200, RESP_STR, RESP_INT, RESP_END);
    addresp(cmd, 201, RESP_END);
    addresp(cmd, 502, RESP_END);
    addresp(cmd, 510, RESP_END);
    cmd = makecmd(L"download");
    addresp(cmd, 200, RESP_INT, RESP_END);
    addresp(cmd, 502, RESP_END);
    addresp(cmd, 510, RESP_END);
    addresp(cmd, 511, RESP_END);
    cmd = makecmd(L"lstrans");
    addresp(cmd, 200, RESP_INT, RESP_INT, RESP_INT, RESP_STR, RESP_STR, RESP_STR, RESP_INT, RESP_INT, RESP_STR, RESP_END);
    addresp(cmd, 201, RESP_END);
    addresp(cmd, 502, RESP_END);
    cmd = makecmd(L"cancel");
    addresp(cmd, 200, RESP_END);
    addresp(cmd, 502, RESP_END);
    addresp(cmd, 512, RESP_END);
    cmd = makecmd(L"notify");
    addresp(cmd, 200, RESP_END);
    addresp(cmd, 501, RESP_END);
    cmd = makecmd(L"sendchat");
    addresp(cmd, 200, RESP_END);
    addresp(cmd, 501, RESP_END);
    addresp(cmd, 502, RESP_END);
    addresp(cmd, 504, RESP_END);
    addresp(cmd, 505, RESP_END);
    addresp(cmd, 509, RESP_END);
    addresp(cmd, 510, RESP_END);
    addresp(cmd, 513, RESP_END);
    cmd = makecmd(L"search");
    addresp(cmd, 200, RESP_INT, RESP_INT, RESP_END);
    addresp(cmd, 501, RESP_END);
    addresp(cmd, 502, RESP_END);
    addresp(cmd, 509, RESP_END);
    addresp(cmd, 510, RESP_END);
    cmd = makecmd(L"cansrch");
    addresp(cmd, 200, RESP_END);
    addresp(cmd, 514, RESP_END);
    cmd = makecmd(L"filtercmd");
    addresp(cmd, 200, RESP_STR, RESP_END);
    addresp(cmd, 201, RESP_END);
    addresp(cmd, 501, RESP_END);
    addresp(cmd, 502, RESP_END);
    addresp(cmd, 504, RESP_END);
    addresp(cmd, 505, RESP_END);
    cmd = makecmd(L"lstrarg");
    addresp(cmd, 200, RESP_STR, RESP_STR, RESP_END);
    addresp(cmd, 201, RESP_END);
    addresp(cmd, 501, RESP_END);
    addresp(cmd, 502, RESP_END);
    addresp(cmd, 512, RESP_END);
    cmd = makecmd(NULL);	/* Nameless notification */
    addresp(cmd, 600, RESP_INT, RESP_INT, RESP_STR, RESP_STR, RESP_STR, RESP_END);	/* FN chat */
    addresp(cmd, 601, RESP_INT, RESP_INT, RESP_END);	/* FN state change */
    addresp(cmd, 602, RESP_INT, RESP_STR, RESP_END);	/* FN name change */
    addresp(cmd, 603, RESP_INT, RESP_END);	/* FN destroy */
    addresp(cmd, 604, RESP_INT, RESP_STR, RESP_END);	/* FN create */
    addresp(cmd, 605, RESP_INT, RESP_INT, RESP_END);	/* FN num peers change */
    addresp(cmd, 610, RESP_INT, RESP_INT, RESP_STR, RESP_STR, RESP_END);	/* Transfer create */
    addresp(cmd, 611, RESP_INT, RESP_INT, RESP_END);	/* Transfer state change */
    addresp(cmd, 612, RESP_INT, RESP_STR, RESP_END);	/* Transfer nick change */
    addresp(cmd, 613, RESP_INT, RESP_INT, RESP_END);	/* Transfer size change */
    addresp(cmd, 614, RESP_INT, RESP_INT, RESP_END);	/* Transfer error update */
    addresp(cmd, 615, RESP_INT, RESP_INT, RESP_END);	/* Transfer progress */
    addresp(cmd, 616, RESP_INT, RESP_STR, RESP_END);	/* Transfer path change */
    addresp(cmd, 617, RESP_INT, RESP_END);	/* Transfer destroy */
    addresp(cmd, 620, RESP_INT, RESP_INT, RESP_END);
    addresp(cmd, 621, RESP_INT, RESP_END);
    addresp(cmd, 622, RESP_INT, RESP_STR, RESP_STR, RESP_STR, RESP_INT, RESP_INT, RESP_INT, RESP_FLOAT, RESP_STR, RESP_END);
    cmd = makecmd(NULL);	/* Nameless connection */
    addresp(cmd, 200, RESP_STR, RESP_END);
    addresp(cmd, 502, RESP_END);
}
