#!/bin/sh

set -e

tempdir="$(mktemp -d /tmp/dc-apkg-XXXXXX)"
cd "$tempdir"
git clone git://git.dolda2000.com/doldaconnect
cd doldaconnect
if [ -n "$1" ]; then
    git checkout "$1"
fi
./bootstrap
./configure

packages="`cat autopackage/build`"
version="`sed -n 's/^.* VERSION "\([^"]*\)".*$/\1/p' config.h`"

for pkg in $packages; do
    sfile="autopackage/$pkg.apspec"
    pname="$(sed -n 's/^ShortName: *\([^ ]\+\)$/\1/p' "$sfile")"
    if [ -z "$pname" ]; then
	echo "makeall: could not find apkg shortname for $sfile" >&2
	exit 1
    fi
    make clean
    PACKAGEFILENAME="$pname.package" makepackage "$sfile"
    mv "$pname-$version.package" "$pname-$version.package.meta" "$pname.xml" "$tempdir"
done

rm -rf "$tempdir/doldaconnect"

echo "packages are in $tempdir"
